services:
  - type: web
    name: grandzone-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npx prisma db push --skip-generate --accept-data-loss && npx tsx prisma/seed.ts; npm start
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres.vmgtlbqxhxxtdoceobue:Supabas8118@aws-1-ap-south-1.pooler.supabase.com:6543/postgres
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 5000
      - key: CLIENT_URL
        value: https://wholesale-xi.vercel.app
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
